services:
  nginx:
    restart: unless-stopped
    build: requirements/nginx/
    image: nginx
    container_name: nginx
    env_file: .env
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpressv:/var/www/wordpress


  mariadb:
    restart: unless-stopped
    build: requirements/mariadb/
    image: mariadb
    container_name: mariadb
    env_file: .env
    networks:
      - inception
    volumes:
      - mariadbv:/var/lib/mysql


  wordpress:
    restart: unless-stopped
    build: requirements/wordpress/
    image: wordpress
    container_name: wordpress
    env_file: .env
    networks:
      - inception
    volumes:
      - wordpressv:/var/www/wordpress
    depends_on:
      - mariadb


  static_web:
    restart: unless-stopped
    build: requirements/bonus/static_web
    image: static_web
    container_name: web
    ports:
      - "440:440"


  adminer:
    restart: unless-stopped
    build: requirements/bonus/adminer
    image: adminer
    container_name: adminer
    env_file: .env
    networks:
      - inception
    volumes:
      - mariadbv:/var/lib/mysql
    ports:
      - "8080:8080"


  redis:
    restart: unless-stopped
    build: requirements/bonus/redis
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - inception


  portainer:
    restart: unless-stopped
    build: requirements/bonus/portainer
    image: portainer
    container_name: portainer
    ports:
      - 9443:9443
      - 9999:9999
    networks:
      - inception
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainerv:/data


  ftp:
    restart: unless-stopped
    build: requirements/bonus/ftp
    image: ftp
    container_name: ftp
    env_file: .env
    ports:
      - 21:21
      - "30000-30010:30000-30010"
    networks:
      - inception
    volumes:
      - wordpressv:/var/www/wordpress


volumes:
  mariadbv:
    name: mariadbv
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/oumondad/data/mariadb'


  wordpressv:
    name: wordpressv
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/oumondad/data/wordpress'


  portainerv:
    name: portainerv
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/oumondad/data/portainer'


networks:
  inception:
    name: 'inception'